name: Testing

on: [push, pull_request]

concurrency:
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}
  group: tests-${{ github.workflow }}-${{ github.ref }}

jobs:
  unit:
    name: Unit Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-command: composer test:unit

#  feature:
#    name: Feature Testing
#    uses: ./.github/workflows/run-test-suite.yml
#    with:
#      fail-fast: true
#      test-command: composer test:feat
#      test-timeout: 20

  functional:
    name: Functional Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-command: composer test:func
      download-binaries: true

  acceptance:
    name: Acceptance Testing
    uses: ./.github/workflows/run-test-suite.yml
    with:
      fail-fast: false
      test-command: composer test:accept
      download-binaries: true
